
# K8s Pod Config

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'vault-agent-injector'
        vault.hashicorp.com/agent-inject-secret-env: 'secret/demo'
        vault.hashicorp.com/agent-inject-template-env: |
          {{ with secret "secret/demo/dummy" }}
            {{ range $key, $value := .Data.data }}
              export {{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
    spec:
      serviceAccountName: vault-agent-injector
      containers:
        - name: demo
          image: alpine:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh",  "-c", "source /vault/secrets/env && sleep infinity"]

